### ISSUE TITLE
EPIC: User Registration

### ISSUE THREAD

**Issue by Al3xandruF** [Al3xandruF/explorers_project-4_fullstack#21]
As a **developer** I need to **create the registration feature** so that **Users can register, login and logout.**

**User Stories:**

- [x] Create registration page.
- [x] Create log in page.
- [x] User can log out.
